//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BWDMS.Salesman
{


    public partial class Bill
    {
        /// <summary>
        /// btnPrint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPrint;

        /// <summary>
        /// gvLines control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvLines;

        /// <summary>
        /// lblDealer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDealer;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblShopAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblShopAddress;

        /// <summary>
        /// litBillDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBillDate;

        /// <summary>
        /// litBillNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBillNumber;

        /// <summary>
        /// litBillTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBillTitle;

        /// <summary>
        /// litDiscount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDiscount;

        /// <summary>
        /// litGrandTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litGrandTotal;

        /// <summary>
        /// litPrintedAt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPrintedAt;

        /// <summary>
        /// litRoute control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRoute;

        /// <summary>
        /// litSalesman control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSalesman;

        /// <summary>
        /// litShop control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litShop;

        /// <summary>
        /// litSubTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSubTotal;
    }
}