//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BWDMS.Dealer
{


    public partial class AddReturn
    {
        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// cvLines control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvLines;

        /// <summary>
        /// ddlCondition control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCondition;

        /// <summary>
        /// ddlOrder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlOrder;

        /// <summary>
        /// lnkCancel control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkCancel;

        /// <summary>
        /// lblHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHeading;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblNoLines control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoLines;

        /// <summary>
        /// lblOrderView control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderView;

        /// <summary>
        /// lblPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageTitle;

        /// <summary>
        /// lblReturnNo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReturnNo;

        /// <summary>
        /// lblSubHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSubHeading;

        /// <summary>
        /// lblViewInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblViewInfo;

        /// <summary>
        /// pnlForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        /// <summary>
        /// pnlLines control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLines;

        /// <summary>
        /// pnlNoLines control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoLines;

        /// <summary>
        /// revReturnDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revReturnDate;

        /// <summary>
        /// rfvOrder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOrder;

        /// <summary>
        /// rfvReason control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvReason;

        /// <summary>
        /// rfvReturnDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvReturnDate;

        /// <summary>
        /// rpLines control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rpLines;

        /// <summary>
        /// txtQty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQty;

        /// <summary>
        /// txtReason control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReason;

        /// <summary>
        /// txtReturnDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReturnDate;
    }
}